# Generated by Django 5.1.6 on 2025-03-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('author', models.CharField(max_length=80)),
                ('price', models.FloatField()),
            ],
        ),
    ]
